# Generated by Django 4.2.16 on 2024-11-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
