# Generated by Django 4.2.16 on 2024-11-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_expense_user_alter_expense_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=120)),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseYear', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
